// Generated: survey photos (30 Aug 2026, 'Foto Biasa' folders) matched to
// station_nodes by visual inspection. Only nodes with a matching photo appear.
const Map<String, List<String>> facilityPhotos = {
  'palmerah_lt1_node_002': ['assets/facilities/P204.jpg'],
  'palmerah_lt1_node_003': ['assets/facilities/P111.jpg'],
  'palmerah_lt1_node_004': ['assets/facilities/P111.jpg'],
  'palmerah_lt1_node_005': ['assets/facilities/P201.jpg'],
  'palmerah_lt1_node_006': ['assets/facilities/P201.jpg'],
  'palmerah_lt1_node_007': ['assets/facilities/P110.jpg'],
  'palmerah_lt1_node_008': ['assets/facilities/P110.jpg'],
  'palmerah_lt1_node_009': ['assets/facilities/P215.jpg'],
  'palmerah_lt1_node_010': ['assets/facilities/P215.jpg'],
  'palmerah_lt2_node_003': ['assets/facilities/H19.jpg'],
  'palmerah_lt2_node_004': ['assets/facilities/H16.jpg'],
  'palmerah_lt2_node_005': ['assets/facilities/H27.jpg'],
  'palmerah_lt2_node_006': ['assets/facilities/H27.jpg'],
  'palmerah_lt2_node_007': ['assets/facilities/H11.jpg'],
  'palmerah_lt2_node_008': ['assets/facilities/H11.jpg'],
  'palmerah_lt2_node_009': ['assets/facilities/H15.jpg'],
  'palmerah_lt2_node_010': ['assets/facilities/H16.jpg'],
  'palmerah_lt2_node_011': ['assets/facilities/H05.jpg'],
  'palmerah_lt2_node_012': ['assets/facilities/H01.jpg', 'assets/facilities/H08.jpg'],
  'palmerah_lt2_node_013': ['assets/facilities/H07.jpg'],
  'palmerah_lt2_node_014': ['assets/facilities/H04.jpg'],
  'palmerah_lt2_node_015': ['assets/facilities/H02.jpg'],
  'palmerah_lt2_node_016': ['assets/facilities/H08.jpg'],
  'palmerah_lt2_node_017': ['assets/facilities/H07.jpg'],
  'palmerah_lt2_node_018': ['assets/facilities/H10.jpg'],
  'palmerah_lt2_node_020': ['assets/facilities/H17.jpg', 'assets/facilities/H30.jpg'],
  'palmerah_lt2_node_021': ['assets/facilities/H30.jpg', 'assets/facilities/H17.jpg'],
  'palmerah_lt2_node_022': ['assets/facilities/H18.jpg'],
  'palmerah_lt2_node_025': ['assets/facilities/H22.jpg', 'assets/facilities/H21.jpg'],
  'palmerah_lt2_node_029': ['assets/facilities/H24.jpg'],
  'palmerah_lt2_node_033': ['assets/facilities/H13.jpg'],
  'palmerah_lt2_node_034': ['assets/facilities/H14.jpg'],
  'palmerah_lt2_node_036': ['assets/facilities/H25.jpg'],
  'palmerah_lt2_node_037': ['assets/facilities/H25.jpg'],
  'palmerah_lt2_node_038': ['assets/facilities/H20.jpg'],
  'palmerah_lt2_node_039': ['assets/facilities/H12.jpg'],
  'palmerah_lt2_node_040': ['assets/facilities/H23.jpg'],
  'palmerah_lt2_node_041': ['assets/facilities/H23.jpg'],
  'palmerah_lt2_node_044': ['assets/facilities/H26.jpg'],
  'palmerah_lt2_node_048': ['assets/facilities/H03.jpg'],
  'palmerah_lt2_node_050': ['assets/facilities/H09.jpg'],
  'palmerah_lt2_node_051': ['assets/facilities/H10.jpg'],
  'palmerah_lt2_node_052': ['assets/facilities/H10.jpg'],
};
